### PR TITLE
add services.convert_identifiers, + minor improvements

### PR DESCRIPTION
**Pull request by lgbouma**
The main addition here is  `services.convert_identifiers`, which contains the functions:  `simbad2gaiadrtwo`, `gaiadrtwo2tic`, and `simbad2tic`.

Plz see the commit strings for further context.

### CODE REVIEW

**Comment by waqasbhatti** [comment]
Thanks for the PR! I'll review this in a bit.

**Comment by waqasbhatti** [comment]
Thanks again for the PR! 

I fixed up some of the commits and merged in your work with these fixes. 

The big changes are in convert_identifiers.py, which I've renamed to identifers.py to match the existing module naming scheme. I've also changed the function names to make them a bit more descriptive and removed the dependencies on ``pandas.read_csv`` (in favor of the existing ``astropy.Table.read`` availability) and on ``astroquery.mast`` (in favor of the existing ``astrobase.services.mast.tic_conesearch`` function). It'd be great if you could check if the updated bits in identifiers.py work as expected for you (or give me a few SIMBAD names to check).

Once we're sure this works as expected, I'll add in the docstrings and update the docs directory for the new module.

**Comment by waqasbhatti** [comment]
I just noticed the tests/test_convert_identifiers.py file, so I've updated that to match the new function scheme in services/identifiers.py. Seems to be testing OK.

**Comment by lgbouma** [comment]
If the tests work, then it's good on my end. Thanks for cleaning up the PR! A few questions for future contributions...

1) why no pandas? In this commit no major pd.DataFrame manipulations were used, but sometimes they can do things that astropy tables can't, in my experience!

2) I see that instead of raising errors, the decision is to log them, and return None. Why? Sometimes, you want a thing to raise an error, and fail, so you can investigate! (OFC the user can still do this in the call, by checking whether the output is not None. But this puts the onus on them, rather than taking care of it inside the package!)

Thanks again!

**Comment by waqasbhatti** [comment]
> 1. why no pandas? In this commit no major pd.DataFrame manipulations were used, but sometimes they can do things that astropy tables can't, in my experience!

No real reason other than personal preference. Some tests were failing because there wasn't an added pandas requirement in setup.py/requirements.txt, so I decided to change out the bits where it was required. astropy.Table is a decent replacement for now in my opinion.

> 2. I see that instead of raising errors, the decision is to log them, and return None. Why? Sometimes, you want a thing to raise an error, and fail, so you can investigate! (OFC the user can still do this in the call, by checking whether the output is not None. But this puts the onus on them, rather than taking care of it inside the package!)

I usually do this in most of the stuff I've written because I don't want things to fail when they're running in a continuous pipeline or under multiprocessing/concurrent.futures. Logging the error condition and returning None is less obtrusive than having to try-except catch a bunch of errors in downstream drivers. 

In this specific case, I think returning None when we don't find a match in the catalog for the requested object is more correct than raising an exception. It's not a "stop-the-world" error, which I think exceptions should be reserved for.

**Comment by lgbouma** [comment]
Inre 2, having been trapped in try-except catching land, this is a good point! Thanks 👍

**Pull request merged**
