### PR TITLE
add services.tesslightcurves

### PR DESCRIPTION
**Pull request by lgbouma**
Main use case: you have some star, and you want a light-curve. And you
want to be flexible about where you're getting it from.

### CODE REVIEW

**Comment by lgbouma** [comment]
(See the tests too)

**Comment by lgbouma** [comment]
PS: if the added dependencies are cause for concern, let me know and I can move this somewhere else.

**Comment by waqasbhatti** [comment]
Thanks for the PR! The added deps aren't really a concern. I took a quick look; it would be good to check the existence of the dependencies in the test module as well before running the tests. See e.g. https://github.com/waqasbhatti/astrobase/blob/7a659c2f2eb5051ec8d6d1471217852d52937f26/tests/test_transitfit.py#L100 

I'll merge this next week.

**Comment by lgbouma** [comment]
Sorry for taking a minute. Done. Also tweaked a few defaults in the eleanor DL for it to work more often (tesscut has bugs, apparently).

**Comment by waqasbhatti** [comment]
Thanks! I'll take a look and merge once I have more reliable internet in a couple of days (travelling right now).

**Comment by waqasbhatti** [comment]
Thanks again for the PR! I'll clean this up if required in a bit.

**Pull request merged**
