### PR TITLE
added savitzky-golay filter and cleaned up lcfit docstrings

### PR DESCRIPTION
**Pull request by lgbouma**
Tested & converged to a result on 100 Kepler EB catalog LCs (all contact EBs, but the actual filter shouldn't have numerical problems for any sharper features).

### CODE REVIEW

**Comment by lgbouma** [comment]
added more parameters to return dict (e.g., savitzky-golay window length) to assess fit residuals.

**Comment by lgbouma** [comment]
missed a case where fourierorder should have been returned.
I think I'm done making commits to this branch (sorry about all the extra modifications!)

**Comment by waqasbhatti** [comment]
Thanks for cleaning this up and adding in the savgol fit function. I'll look this over and merge it later tonight. May make some changes after, but not big ones.

**Comment by lgbouma** [comment]
Per the email -- need phase-sorted times to reconstruct the time series in whatever's calling these fitting routines.

**Pull request merged**
